name: deploy
on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type : string

env: 
  environment: ${{ inputs.environment }}

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: do-work
        run: echo "Hello $environment!"
        
